### ISSUE TITLE
when the source code will be released?

### ISSUE THREAD

**Issue by hubery1619** [naver-ai/cl-vs-mim#1]
Hi,
Your work is quite fascinating. May I inquire as to when the source code will be released? Thank you very much.

**Comment by xxxnell** [comment]
Hi @hubery1619,

Thank you for your patience and support. I apologize for the delayed release of the code; we needed some time to review the license in order to ensure compliance with our company's policy. We have now released the code, and we will be updating it as soon as possible to enable it to run on Google Colab with documentations.
